### ISSUE TITLE
Cannot run multiple tippecanoe calls to create tiles with the same layer name

### ISSUE THREAD

**Issue by laurenoldham1202** [walkerke/mapboxapi#11]
Howdy!

I'm trying to use tippecanoe in R to generate tiles in my workflow. I'm having issues giving different tilesets the same layer name. My script involves generating tiles at different zoom levels and resolutions, but they have the same layer/attribute that needs to be named consistently. With tippecanoe, I can accomplish this easily with the calls:

```
tippecanoe -z4 -Z3 -f -r1 -aL -ab -l abundance -o example_26km.mbtiles -s EPSG:4326 26_km.geojson
tippecanoe -z2 -Z0 -f -r1 -aL -ab -l abundance -o example_77km.mbtiles -s EPSG:4326 77_km.geojson
```

I try to run the equivalent in R, wherein the geojson files are sf objects:
```
tippecanoe(input = sf_26,
           output = 'r_26km.mbtiles',
           layer_name = 'abundance',
           min_zoom = 3,
           max_zoom = 4,
           overwrite = T,
           keep_geojson = F)

tippecanoe(input = sf_77,
           output = 'r_77km.mbtiles',
           layer_name = 'abundance',
           min_zoom = 0,
           max_zoom = 2,
           overwrite = T,
           keep_geojson = F)
```

When I set the same `layer_name`, I get the error:
```
tippecanoe v1.36.0
Layer abundance in dataset /var/folders/mw/lqp43q_n34dbq9_0rjcpfwtwlkfyrh/T//Rtmp33I8XI/abundance.geojson already exists:
use either append=TRUE to append to layer or append=FALSE to overwrite layer
Error in CPL_write_ogr(obj, dsn, layer, driver, as.character(dataset_options),  : 
  Dataset already exists.
```

It appears that there is some sort of `sf_write` call in the tippecanoe fn that needs to have the `append` argument set so that multiple tilesets can be generated with the same layer name. Is this possible to add?

**Comment by walkerke** [comment]
Hi @laurenoldham1202 - thanks for filing!  I've pushed a commit that fixes this on my end.  Would you mind installing from GitHub and testing this out?
