### ISSUE TITLE
Request: Add tippecanoe `tile-join` call

### ISSUE THREAD

**Issue by laurenoldham1202** [walkerke/mapboxapi#12]
Hello again!

Once again, I am trying to fully integrate some simple tippecanoe calls into an R script. I am hoping that the [tile-join](https://github.com/mapbox/tippecanoe#tile-join) call can be added to `mapboxapi`. For my personal needs, simply having inputs for output (`-o`), forcing overwrites (`-o`), and tilesets to be joined is sufficient, though there are many different options that could be included.

For example, my basic tile-join call is something like:
```
tile-join -f -o all-resolutions.mbtiles 77km-res.mbtiles 26km-res.mbtiles 9km-res.mbtiles
```

I would expect a tile-join R function to look something like:
```
mapboxapi::tile_join(output = 'all-resolutions', force = T, tilesets = c('77km-res', '26km-res', '9km-res'))
```

Hoping this is useful for other folks too. Very happy to have this package and hope that it's feasible to add this call! :)

**Comment by walkerke** [comment]
I'm focusing my dev efforts for this package on Mapbox Tiling Service (#10) as Mapbox is no longer developing tippecanoe.  However, I'd welcome a PR from someone in the community who uses it!
