### ISSUE TITLE
Issue with Installing Tippecanoe - Mac, system(), + homebrew

### ISSUE THREAD

**Issue by mrworthington** [walkerke/mapboxapi#14]
Hey Kyle,

I know this is probably just isolated to my computer, because I can't find anything to solve my problem, but I got the same error message as #7 : "Error: tippecanoe is not installed. Please visit https://github.com/mapbox/tippecanoe for installation instructions."

The weird thing is that if I go to any of my terminals and I use Bash or Zsh to type "tippecanoe -v", I get the following:

`tippecanoe v1.36.0`

If I try to run `system("tippecanoe -v")`, I get this:

```
> system ("tippecanoe -v")
sh: tippecanoe: command not found
Warning message:
In system("tippecanoe -v") : error in running command
```

For context I'm on an ARM Mac, but I think this is a path issue. Because if I run `system("tippecanoe -v")`, it'll tell me it doesn't recognize the `brew` command. 

Have you encountered this?

**Comment by walkerke** [comment]
Closing as I'm handling over in #7
