### ISSUE TITLE
Is it possible to add an `mb_distance` function?

### ISSUE THREAD

**Issue by Rmadillo** [walkerke/mapboxapi#15]
Hi,

I was wondering if it is possible to add an `mb_distance` function that would operate like the `mb_isochrone` function, only it would return distance instead of travel time? It looks like the Mapbox API does support this (https://docs.mapbox.com/api/navigation/isochrone/), but I am not sure how to adjust your code to make it work, especially since the API will only return time or distance, but not both at the same time. 

Thanks for considering it!

**Comment by walkerke** [comment]
Thanks for the heads up!  This would be a great new feature.  I'll implement it in `mb_isochrone()` but allow for distance intervals instead of time intervals.  I'll let you know when it's ready.

**Comment by walkerke** [comment]
This is now implemented and on CRAN!

**Comment by Rmadillo** [comment]
Thank you so much!
