### ISSUE TITLE
Error installing mb access token

### ISSUE THREAD

**Issue by jzadra** [walkerke/mapboxapi#19]
When I run `mb_access_token("my_token", install = TRUE, overwrite = T)` I get:

Your original .Renviron will be backed up and stored in your R HOME directory if needed.
Error in read.table(renv, stringsAsFactors = FALSE) : 
  no lines available in input

> session_info()
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.1.2 (2021-11-01)
 os       macOS Monterey 12.3
 system   x86_64, darwin17.0
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Denver
 date     2022-03-31
 rstudio  2021.09.1+372 Ghost Orchid (desktop)
 pandoc   NA

**Comment by walkerke** [comment]
What do you see when you call `usethis::edit_r_environ()`?
