### ISSUE TITLE
Feature suggestion: add support for alternate buffer_dist units + other new `static_mapbox()` enhancements

### ISSUE THREAD

**Issue by elipousson** [walkerke/mapboxapi#28]
It would be nice to allow `static_mapbox()` to support a `unit` argument that defined the `buffer_dist` unit (currently always meters) or allow buffer_dist to accept units class objects that use a distance unit. I've implemented this feature in my own {overedge} package (e.g. [`st_bbox_ext()`](https://elipousson.github.io/overedge/reference/st_bbox_ext.html) supports a `dist` buffer based on `unit`) using the [`convert_dist_units()`](https://elipousson.github.io/overedge/reference/convert_dist_units.html) function.

I'd be happy to re-implement `convert_dist_units()` as a utility function for {mapboxapi} to add this feature to `static_mapbox()`.

The other feature I'd like to add to `static_mapbox()` is support for named colors for overlay_style rather than hex codes only. I figured out how to write a `col2hex()` utility function that should be easy to add to the [`set_static_map_overlay()`](https://github.com/walkerke/mapboxapi/blob/master/R/maps.R#L778) utility function:

```
col2hex <- function(color) {
  grDevices::rgb(t(grDevices::col2rgb(color)), maxColorValue = 255)
}
```

If this sounds good, I can add these enhancements to #27 – I just didn't want to mix a bug fix PR with a new feature PR without checking if you wanted it first.

**Comment by walkerke** [comment]
Yes, that'd be great!  I appreciate your work on all these new features; I'm doing some maintenance for a new CRAN submission so now's a good time.

**Comment by elipousson** [comment]
I added these changes along with some minor refactoring and one additional new feature: a new `tm_static_mapbox()` function that wraps `tmap::tm_rgb`. I also added tests for the new helper functions. Let me know if you spot any issues or encounter any errors!

**Comment by walkerke** [comment]
looks excellent!  I'm noticing that `tm_static_mapbox()` (which looks great) is not exported.  I'll go ahead and merge then push a fix for this right afterwards.

**Comment by elipousson** [comment]
Great! I did have one small second thought on the parameter names. Should `units` be named `unit` to avoid confusion with the units parameter in ggplot? I used `unit` for the {overedge} package but `units` is more intuitive so I basiclaly defaulted back to that without thinking too much about it.

**Comment by walkerke** [comment]
@elipousson I wouldn't worry too much about that.  The package is passing all checks / tests so I'm going to ship off version 0.4 to CRAN, probably today.
