### ISSUE TITLE
Could not find function "mapview"

### ISSUE THREAD

**Issue by MandleDan** [walkerke/mapboxapi#52]
Trying to run some maps using Kyle's AWESOME notes from his GeoIntelligence workshop last month. Unfortunately in the meantime having a problem getting the "mapview" function to operate. Are others seeing this as well? Curious how to overcome this and keep mapping!

Error in mapview(dataset_name) : could not find function "mapview"

**Comment by robbfitzsimmons** [comment]
Sounds like the [`mapview`](https://r-spatial.github.io/mapview/) package might not be loaded in the current environment, which is causing it to not find the function.

Try loading the package at the beginning of every session:
```R
library(mapview)
```

If you get an error that `mapview` is not installed, you can run the following:

```R
install.packages("mapview")
```

Best of luck!

**Comment by MandleDan** [comment]
Rookie mistake on my part. Must be time to shut it down and start the July Fourth Holiday! Thanks @robbfitzsimmons!
