### ISSUE TITLE
Error: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by chrislim5** [walkerke/mapboxapi#6]
I'm getting an error when trying to use list_styles() or get_vector_tiles() "Error: $ operator is invalid for atomic vectors"
I've installed my access token using mb_access_token() and restarted before trying to use the functions. Any help is appreciated.

**Comment by walkerke** [comment]
Would you be able to provide a reproducible example that I could test?  I think I've fixed this in `get_vector_tiles()` so I'd recommend re-installing and trying again.
