### ISSUE TITLE
tippecanoe question

### ISSUE THREAD

**Issue by schoewed** [walkerke/mapboxapi#9]
This package is awesome! For the tippecanoe function, is there any way to add a TRUE/FALSE input to "keep densest or drop densest as needed"? Or is this in other options?

**Comment by walkerke** [comment]
Yes you can use it!  tippecanoe has so many options that I only made native R arguments for what I thought would be the most common.  Anything else can be specified like you would on the command line within a character string that you pass to the `other_options` argument.  For example, modifying the example in the documentation slightly: 

```r
library(tidycensus)
library(sf)
library(mapboxapi)

# Get population data for Census tracts in Vermont
vt_population <- get_decennial(
  geography = "tract",
  variables = "P001001",
  state = "Vermont",
  year = 2010,
  geometry = TRUE
)

# Convert to representative dots - 1 per person
vt_dots <- st_sample(
  vt_population,
  size = vt_population$value
)

# Use tippecanoe to create dynamic tiles, dropping dots in the densest areas as needed
tippecanoe(
  input = vt_dots,
  output = "vt_drop_densest.mbtiles",
  layer_name = "vermont_population",
  max_zoom = 16,
  other_options = "--drop-densest-as-needed"
)

# Upload to your Mapbox account for visualization
# A Mapbox secret access token must be set with mb_access_token()
# to upload data to your account
upload_tiles(
  input = "vt_drop_densest.mbtiles",
  username = "kwalkertcu",
  tileset_id = "vt_drop_densest",
  multipart = TRUE
)
```

![vt_tippecanoe](https://user-images.githubusercontent.com/4872833/96039029-a9cc7c80-0e2d-11eb-94fb-60993406e6fa.gif)

**Comment by schoewed** [comment]
Awesome, thanks for your response, Kyle! Your MUSA class was great.

DANA SCHOEWE
Senior Associate

RCLCO
7200 Wisconsin Avenue, Suite 1110
Bethesda, MD 20814
O: (240) 206-6306
Ext. 4006 (Internal)
M: (224) 234-1322
W: RCLCO.COM <http://www.rclco.com/>

RCLCO’s mission is to help clients make strategic, effective and enduring decisions about real estate. Since our formation in 1967, we have been proudly serving the best minds in real estate with cutting-edge analytics and actionable advice. Our work includes market, economic, financial and impact analyses; investment portfolio strategy and implementation; and management consulting.

The information contained in this e-mail message is confidential and may be legally privileged. It is intended only for the use of the individual or entity named above. If you receive this in error please contact the sender immediately and delete any material from your computer. Thank you for your cooperation and consideration.
